name: CI - Build and Test

defaults:
  run:
    shell: bash

on: [push, pull_request, workflow_dispatch]

jobs:

  static-analysis-check:
    name: Static Analysis
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
#      - uses: pre-commit/action@v2.0.3
#        with:
#          extra_args: --verbose --config=confs/.pre-commit-config.yaml

  build:
    name: Build tool
    runs-on: ${{ matrix.os }}
    needs: static-analysis-check
    strategy:
      fail-fast: true
      matrix:
        os:
          - 'ubuntu-latest'
          #- 'macos-latest'
          #- 'windows-latest'
        python-version:
          - '3.6'
          #- '3.7'
          #- '3.8'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64

      - name: Install
        run: |
          pip install -e .
          pip install -r requirements/requirements_dev.txt
      - name: Run tests
        run: pytest